# Generated by Django 5.1.3 on 2024-12-11 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmessage',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.event'),
            preserve_default=False,
        ),
    ]
