# Generated by Django 5.1.3 on 2024-12-11 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventparticipant_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmessage',
            name='event',
        ),
        migrations.AlterField(
            model_name='eventmessage',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_received_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
