# Generated by Django 5.1.3 on 2024-12-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventmessage_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmessage',
            name='receiver',
        ),
    ]
